"""empty message

Revision ID: 894f439c99ac
Revises: d96a2949551a
Create Date: 2018-11-28 21:08:22.967144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894f439c99ac'
down_revision = 'd96a2949551a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('performance_rating', sa.Float(), nullable=True))
    op.add_column('answers', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    op.drop_column('answers', 'time')
    op.drop_column('answers', 'performance_rating')
    # ### end Alembic commands ###
