"""empty message

Revision ID: fcaa99f16409
Revises: ca36f90a3b59
Create Date: 2018-12-04 20:44:25.343235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaa99f16409'
down_revision = 'ca36f90a3b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'body_html')
    # ### end Alembic commands ###
